### ISSUE TITLE
cUnhandled TypeErrorccccbggkvehttddrftujlvknvnvujnutdtunfijgjit

### ISSUE THREAD

**Issue by jeder** [flowkeeper-org/fk-desktop#37]
Was running the tutorial and hit the "Play" key... had a little error...

```
Traceback (most recent call last):
  File "fk/qt/qt_timer.py", line 57, in <lambda>
  File "fk/qt/qt_timer.py", line 64, in _call
TypeError: Tutorial._on_pomodoro_work_start.<locals>.do() takes 1 positional argument but 2 were given
```

**Comment by co-stig** [comment]
Thanks @jeder, I was able to reproduce this error and fixed it in [v0.8.1](https://github.com/flowkeeper-org/fk-desktop/releases/tag/v0.8.1), which is now available for download.
